/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Store;

import hany.DBConnect;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author amnassar
 */
public final class moveorder extends javax.swing.JInternalFrame {

    /**
     * Creates new form book
     */
    PreparedStatement pst;
    ResultSet rs;
    public String y;
   public Calendar cal;
    public int day;
    public int month;
    public int year;
    String dayyy;
    public String datee;
    public String fulldatee;

    public moveorder() {
        initComponents();
        tablelord();
        clear();
        TableCellRenderer rendererFromHeader = tdetails.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tdetails.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tdetails.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tdetails.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tdetails.getTableHeader().setOpaque(false);
        tdetails.getTableHeader().setBackground(new Color(28,57,81));
        tdetails.getTableHeader().setForeground(new Color(255, 255, 255));
        tdetails.getTableHeader().setPreferredSize(new Dimension(40, 40));
        tdetails.setRowHeight(40);
        Calendar cal = new GregorianCalendar();
        day = cal.get(Calendar.DAY_OF_MONTH);
        month = cal.get(Calendar.MONTH) + 1;
        year = cal.get(Calendar.YEAR);
        number.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        Font bigFont = new Font("Arial", Font.BOLD, 30); // or whatever
        tdetails.getTableHeader().setFont(bigFont);
        items() ;
          cal = new GregorianCalendar();
            int dayy = cal.get(Calendar.DAY_OF_MONTH);
            dayyy = String.valueOf(dayy);
            if (dayy == 1 || dayy == 2 || dayy == 3 || dayy == 4
                    || dayy == 5 || dayy == 6 || dayy == 7 || dayy == 8 || dayy == 9) {
                dayyy = String.valueOf(dayy);
                dayyy = "0" + dayyy;
            }
            int month = cal.get(Calendar.MONTH) + 1;
            int year = cal.get(Calendar.YEAR);
            date1.setText(year + "-" + month + "-" + dayyy);
            datee = date1.getText().toString();
            TimeZone tz = TimeZone.getTimeZone("GMT+02");
            Calendar c = Calendar.getInstance(tz);
            String time = String.format("%02d", c.get(Calendar.HOUR_OF_DAY)) + ":"
                    + String.format("%02d", c.get(Calendar.MINUTE));
            fulldatee = datee + " " + time;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel14 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tdetails = new javax.swing.JTable();
        autoserial4 = new javax.swing.JLabel();
        cmitem = new javax.swing.JComboBox();
        available = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        delete4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        save4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        serialid4 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        numberrr = new javax.swing.JLabel();
        nameee = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1060, 660));
        setMinimumSize(new java.awt.Dimension(1060, 660));
        setPreferredSize(new java.awt.Dimension(1060, 660));

        jPanel14.setBackground(new java.awt.Color(0, 0, 0));
        jPanel14.setForeground(new java.awt.Color(255, 255, 255));
        jPanel14.setMaximumSize(new java.awt.Dimension(1060, 660));
        jPanel14.setMinimumSize(new java.awt.Dimension(1060, 660));
        jPanel14.setPreferredSize(new java.awt.Dimension(1060, 660));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tdetails.setBackground(new java.awt.Color(102, 152, 205));
        tdetails.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tdetails.setForeground(new java.awt.Color(255, 255, 255));
        tdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "التاريخ", "العدد", "المنتج", "id"
            }
        ));
        tdetails.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tdetails.setRowHeight(25);
        tdetails.setRowMargin(2);
        tdetails.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tdetails.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tdetailsMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tdetails);
        if (tdetails.getColumnModel().getColumnCount() > 0) {
            tdetails.getColumnModel().getColumn(1).setMinWidth(100);
            tdetails.getColumnModel().getColumn(1).setPreferredWidth(100);
            tdetails.getColumnModel().getColumn(1).setMaxWidth(100);
            tdetails.getColumnModel().getColumn(3).setMinWidth(1);
            tdetails.getColumnModel().getColumn(3).setPreferredWidth(1);
            tdetails.getColumnModel().getColumn(3).setMaxWidth(1);
        }

        jPanel14.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 600, 330));

        autoserial4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        autoserial4.setForeground(new java.awt.Color(255, 255, 255));
        autoserial4.setText("لإثسف");
        jPanel14.add(autoserial4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 170, 60));

        cmitem.setEditable(true);
        cmitem.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        cmitem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));
        cmitem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmitemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmitemMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmitemMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmitemMouseReleased(evt);
            }
        });
        cmitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmitemActionPerformed(evt);
            }
        });
        cmitem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmitemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmitemKeyReleased(evt);
            }
        });
        jPanel14.add(cmitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 210, 40));

        available.setEditable(false);
        available.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        available.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel14.add(available, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 80, 40));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel37.setText("المنتج");
        jPanel14.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 70, 40));

        delete4.setBackground(new java.awt.Color(102, 152, 205));
        delete4.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        delete4.setForeground(new java.awt.Color(255, 255, 255));
        delete4.setText("مسح");
        delete4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete4ActionPerformed(evt);
            }
        });
        jPanel14.add(delete4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 120, 40));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setText("العدد");
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 140, 40));

        number.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel14.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 120, 80, 40));

        save4.setBackground(new java.awt.Color(102, 152, 205));
        save4.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        save4.setForeground(new java.awt.Color(255, 255, 255));
        save4.setText("حفظ");
        save4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save4ActionPerformed(evt);
            }
        });
        jPanel14.add(save4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 120, 40));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nYwGq3.jpg"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel14.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 730));

        serialid4.setText("jLabel1");
        jPanel14.add(serialid4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 650, -1, -1));

        date4.setText("jLabel1");
        jPanel14.add(date4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, -1, -1));

        date1.setText("jLabel1");
        jPanel14.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, -1, -1));

        numberrr.setText("jLabel1");
        jPanel14.add(numberrr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 690, -1, -1));

        nameee.setText("jLabel2");
        jPanel14.add(nameee, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 660, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tdetailsMouseClicked
        DefaultTableModel tmodel = (DefaultTableModel) tdetails.getModel();
        int selectrowindex = tdetails.getSelectedRow();
        serialid4.setText(tmodel.getValueAt(selectrowindex, 3).toString());
        numberrr.setText(tmodel.getValueAt(selectrowindex, 1).toString());
        nameee.setText(tmodel.getValueAt(selectrowindex, 2).toString());
    }//GEN-LAST:event_tdetailsMouseClicked

    private void delete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete4ActionPerformed
        if (serialid4.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "اختر النوع المراد مسحة");

        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "حفظ العملية ؟", "رسالة تاكيد ", dialogButton);
            if (dialogResult == 0) {
                try {
                    String sql = "DELETE FROM cafe.storeitemlogs WHERE id='" + serialid4.getText() + "'";
                    pst = (PreparedStatement) DBConnect.con.prepareStatement(sql);
                    pst.execute();
                    String sqla1 = "UPDATE cafe.storeitemlist SET number =number+"+numberrr.getText()+" WHERE  name='" + nameee.getText() + "'";
                    pst = (PreparedStatement) DBConnect.con.prepareStatement(sqla1);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, " تم مسح العملية بنجاح");
                    tablelord();
                    clear();
                } catch (SQLException ex) {

                }
                clear();
            } else {

                JOptionPane.showMessageDialog(this, "الغاء العملية ");
            }
        }
    }//GEN-LAST:event_delete4ActionPerformed

    private void save4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save4ActionPerformed
        try {
            int numberr = Integer.parseInt(number.getText());
             String item = cmitem.getSelectedItem().toString();
            if (serialid4.getText().trim().isEmpty()) {

                if (cmitem.getSelectedItem().toString().equals("-") || numberr <0) {
                    JOptionPane.showMessageDialog(this, " من فضلك ادخل سم المنتج والعدد ");
                } else {
                    if(Integer.parseInt(available.getText()) > Integer.parseInt(number.getText()) )
                    {
                    int dialogButton = JOptionPane.YES_NO_OPTION;
                    int dialogResult = JOptionPane.showConfirmDialog(this, "حفظ العملية ؟", "رسالة تاكيد ", dialogButton);
                    if (dialogResult == 0) {
                        try {
                            String sql = "INSERT INTO  cafe.storeitemlogs (name,number,date,fulldate,type) VALUES"
                                    + " ('" + item + "','"+number.getText()+"','"+datee+"','"+fulldatee+"','صرف من المخزن')";
                            pst = (PreparedStatement) DBConnect.con.prepareStatement(sql);
                            pst.execute();
                             String sqla1 = "UPDATE cafe.storeitemlist SET number =number-"+numberr+" WHERE  name='" + item + "'";
                    pst = (PreparedStatement) DBConnect.con.prepareStatement(sqla1);
                    pst.executeUpdate();
                            JOptionPane.showMessageDialog(null, "تم تسجيل اذن الصرف  بنجاح");
                            tablelord();
                            clear();
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "الغاء العملية");

                    }
                }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "لا يوجد عدد كافي بالمخزن");
                    }
                }
            } 

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, " ادخل عدد صحيح ");
        }
    }//GEN-LAST:event_save4ActionPerformed

    private void cmitemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmitemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmitemMouseClicked

    private void cmitemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmitemMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmitemMouseEntered

    private void cmitemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmitemMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmitemMousePressed

    private void cmitemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmitemMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmitemMouseReleased

    private void cmitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmitemActionPerformed
                         Object obj = evt.getSource();
       if(obj==cmitem)
       {   
           
              try {
                  String sqll="SELECT number  FROM cafe.storeitemlist where  name='"+cmitem.getSelectedItem().toString()+"'";
                  
                  pst=(PreparedStatement) DBConnect.con.prepareStatement(sqll);
                  
                  rs=pst.executeQuery();
                  
                  while(rs.next()){
                      
                     available.setText(rs.getString("number"));
                      
                  }
              } catch (SQLException ex) {
              }
                  }
    }//GEN-LAST:event_cmitemActionPerformed

    private void cmitemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmitemKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmitemKeyPressed

    private void cmitemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmitemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cmitemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autoserial4;
    private javax.swing.JTextField available;
    private javax.swing.JComboBox cmitem;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date4;
    private javax.swing.JButton delete4;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel nameee;
    private javax.swing.JTextField number;
    private javax.swing.JLabel numberrr;
    private javax.swing.JButton save4;
    private javax.swing.JLabel serialid4;
    private javax.swing.JTable tdetails;
    // End of variables declaration//GEN-END:variables

    public void tablelord() {
        try {
            String sqll = "SELECT * FROM cafe.storeitemlogs where date= '"+datee+"' and type = 'صرف من المخزن'";
            pst = (PreparedStatement) DBConnect.con.prepareStatement(sqll);
            rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tdetails.getModel();
            model.setRowCount(0);
            int x = 1;
            while (rs.next()) {
                Object row[] = {
                   rs.getString("fulldate"),
                    rs.getString("number"),
                    rs.getString("name"),
                    rs.getString("id"),
                };
                model.addRow(row);
                x++;

            }
            if (x >= 11) {
            } else {
                for (int z = x; z < 13; z++) {
                    Object rowData[] = {
                        "", "", "", "", "",};
                    model.addRow(rowData);
                }
            }
        } catch (SQLException ex) {

        }
    }
    public void items() {
        try {
            String sql = "SELECT * FROM cafe.storeitemlist where type='استخدام' and number >0";
            pst = (PreparedStatement) DBConnect.con.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                String namee = rs.getString("name");

                cmitem.addItem(namee);

            }

        } catch (SQLException ex) {

        }
    }

    public void clear() {
        number.setText("1");
        available.setText("0");
        cmitem.setSelectedIndex(0);
        serialid4.setText("");
    }

}
