/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//mp3.stop();
package hany;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.year;
import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author amnassar
 */
public final class people extends javax.swing.JInternalFrame {

    /**
     * Creates new form book
     */
    PreparedStatement pst;
    ResultSet rs;
    public String y;
    public String check;
    public String datee;
    public Calendar cal;
    public String pphone1;
    public String pphone2;
    public String ppp2;
    public String ppp1;
    public String ttt1;
    public String ttt2;

    String dayyy;
    public static Room1 room1;
    public static Room2 room2;
    public static Room3 room3;
    public static Room4 room4;
    public static Room5 room5;
    public static Room6 room6;

    public people() throws ParseException {
        initComponents();
        try {
            room1 = new Room1();
            room2 = new Room2();
            room3 = new Room3();
            room4 = new Room4();
            room5 = new Room5();
            room6 = new Room6();
        } catch (IOException ex) {
            Logger.getLogger(people.class.getName()).log(Level.SEVERE, null, ex);
        }

        cal = new GregorianCalendar();

        int month = cal.get(Calendar.MONTH) + 1;
        int year = cal.get(Calendar.YEAR);
        int dayy = cal.get(Calendar.DAY_OF_MONTH);
        dayyy = String.valueOf(dayy);
        if (dayy == 1 || dayy == 2 || dayy == 3 || dayy == 4
                || dayy == 5 || dayy == 6 || dayy == 7 || dayy == 8 || dayy == 9) {
            dayyy = String.valueOf(dayy);
            dayyy = "0" + dayyy;
        }
        date1.setText(year + "-" + month + "-" + dayyy);
        datee = date1.getText().toString();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serialid = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        roomalarm6 = new javax.swing.JButton();
        fulltimepanel6 = new javax.swing.JPanel();
        fulltime6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        roomps6 = new javax.swing.JButton();
        roomalarm5 = new javax.swing.JButton();
        fulltimepanel5 = new javax.swing.JPanel();
        fulltime5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        roomps5 = new javax.swing.JButton();
        roomps4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        fulltimepanel4 = new javax.swing.JPanel();
        fulltime4 = new javax.swing.JLabel();
        roomalarm4 = new javax.swing.JButton();
        roomalarm3 = new javax.swing.JButton();
        fulltimepanel3 = new javax.swing.JPanel();
        fulltime3 = new javax.swing.JLabel();
        roomps3 = new javax.swing.JButton();
        roomalarm2 = new javax.swing.JButton();
        fulltimepanel2 = new javax.swing.JPanel();
        fulltime2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        roomps2 = new javax.swing.JButton();
        roomps1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fulltimepanel1 = new javax.swing.JPanel();
        fulltime1 = new javax.swing.JLabel();
        roomalarm1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        serialid.setText("jLabel1");

        date1.setText("date");

        setMaximumSize(new java.awt.Dimension(1060, 750));
        setMinimumSize(new java.awt.Dimension(1060, 750));
        setPreferredSize(new java.awt.Dimension(1060, 750));

        jPanel10.setBackground(new java.awt.Color(28, 57, 81));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setMaximumSize(new java.awt.Dimension(1060, 750));
        jPanel10.setMinimumSize(new java.awt.Dimension(1060, 750));
        jPanel10.setPreferredSize(new java.awt.Dimension(1060, 750));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(21, 31, 41));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Room 3");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 240, 50));

        roomalarm6.setBackground(new java.awt.Color(21, 31, 41));
        roomalarm6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        roomalarm6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/stopwatch_1.png"))); // NOI18N
        roomalarm6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomalarm6ActionPerformed(evt);
            }
        });
        jPanel10.add(roomalarm6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 570, 60, 40));

        fulltimepanel6.setBackground(new java.awt.Color(204, 204, 204));
        fulltimepanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fulltime6.setBackground(new java.awt.Color(102, 152, 205));
        fulltime6.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        fulltime6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fulltime6.setText("0");
        fulltimepanel6.add(fulltime6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        jPanel10.add(fulltimepanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 570, 170, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(21, 31, 41));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Room 6");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 240, 50));

        roomps6.setBackground(new java.awt.Color(99, 188, 231));
        roomps6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vr-glasses.png"))); // NOI18N
        roomps6.setToolTipText("");
        roomps6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        roomps6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomps6ActionPerformed(evt);
            }
        });
        jPanel10.add(roomps6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 240, 170));

        roomalarm5.setBackground(new java.awt.Color(21, 31, 41));
        roomalarm5.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        roomalarm5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/stopwatch_1.png"))); // NOI18N
        roomalarm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomalarm5ActionPerformed(evt);
            }
        });
        jPanel10.add(roomalarm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 60, 40));

        fulltimepanel5.setBackground(new java.awt.Color(204, 204, 204));
        fulltimepanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fulltime5.setBackground(new java.awt.Color(102, 152, 205));
        fulltime5.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        fulltime5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fulltime5.setText("0");
        fulltimepanel5.add(fulltime5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        jPanel10.add(fulltimepanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 170, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(21, 31, 41));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Room 5");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 240, 50));

        roomps5.setBackground(new java.awt.Color(99, 188, 231));
        roomps5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vr-glasses.png"))); // NOI18N
        roomps5.setToolTipText("");
        roomps5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        roomps5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomps5ActionPerformed(evt);
            }
        });
        jPanel10.add(roomps5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 240, 170));

        roomps4.setBackground(new java.awt.Color(99, 188, 231));
        roomps4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vr-glasses.png"))); // NOI18N
        roomps4.setToolTipText("");
        roomps4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        roomps4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomps4ActionPerformed(evt);
            }
        });
        jPanel10.add(roomps4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 240, 170));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(21, 31, 41));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Room 4");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 240, 50));

        fulltimepanel4.setBackground(new java.awt.Color(204, 204, 204));
        fulltimepanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fulltime4.setBackground(new java.awt.Color(102, 152, 205));
        fulltime4.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        fulltime4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fulltime4.setText("0");
        fulltimepanel4.add(fulltime4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        jPanel10.add(fulltimepanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, 170, 40));

        roomalarm4.setBackground(new java.awt.Color(21, 31, 41));
        roomalarm4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        roomalarm4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/stopwatch_1.png"))); // NOI18N
        roomalarm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomalarm4ActionPerformed(evt);
            }
        });
        jPanel10.add(roomalarm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 60, 40));

        roomalarm3.setBackground(new java.awt.Color(21, 31, 41));
        roomalarm3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        roomalarm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/stopwatch_1.png"))); // NOI18N
        roomalarm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomalarm3ActionPerformed(evt);
            }
        });
        jPanel10.add(roomalarm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, 60, 40));

        fulltimepanel3.setBackground(new java.awt.Color(204, 204, 204));
        fulltimepanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fulltime3.setBackground(new java.awt.Color(102, 152, 205));
        fulltime3.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        fulltime3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fulltime3.setText("0");
        fulltimepanel3.add(fulltime3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        jPanel10.add(fulltimepanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 170, 40));

        roomps3.setBackground(new java.awt.Color(99, 188, 231));
        roomps3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vr-glasses.png"))); // NOI18N
        roomps3.setToolTipText("");
        roomps3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        roomps3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomps3ActionPerformed(evt);
            }
        });
        jPanel10.add(roomps3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 240, 170));

        roomalarm2.setBackground(new java.awt.Color(21, 31, 41));
        roomalarm2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        roomalarm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/stopwatch_1.png"))); // NOI18N
        roomalarm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomalarm2ActionPerformed(evt);
            }
        });
        jPanel10.add(roomalarm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 60, 40));

        fulltimepanel2.setBackground(new java.awt.Color(204, 204, 204));
        fulltimepanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fulltime2.setBackground(new java.awt.Color(102, 152, 205));
        fulltime2.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        fulltime2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fulltime2.setText("0");
        fulltimepanel2.add(fulltime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        jPanel10.add(fulltimepanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 170, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(21, 31, 41));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Room 2");
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 240, 50));

        roomps2.setBackground(new java.awt.Color(99, 188, 231));
        roomps2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vr-glasses.png"))); // NOI18N
        roomps2.setToolTipText("");
        roomps2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        roomps2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomps2ActionPerformed(evt);
            }
        });
        jPanel10.add(roomps2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 240, 170));

        roomps1.setBackground(new java.awt.Color(99, 188, 231));
        roomps1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vr-glasses.png"))); // NOI18N
        roomps1.setToolTipText("");
        roomps1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        roomps1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomps1ActionPerformed(evt);
            }
        });
        jPanel10.add(roomps1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 240, 170));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(21, 31, 41));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Room 1");
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 240, 50));

        fulltimepanel1.setBackground(new java.awt.Color(204, 204, 204));
        fulltimepanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fulltime1.setBackground(new java.awt.Color(102, 152, 205));
        fulltime1.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        fulltime1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fulltime1.setText("0");
        fulltimepanel1.add(fulltime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 40));

        jPanel10.add(fulltimepanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 170, 40));

        roomalarm1.setBackground(new java.awt.Color(21, 31, 41));
        roomalarm1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        roomalarm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exstopwatch/stopwatch_1.png"))); // NOI18N
        roomalarm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomalarm1ActionPerformed(evt);
            }
        });
        jPanel10.add(roomalarm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 60, 40));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nYwGq3.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 2));
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 1080, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomps1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomps1ActionPerformed
        if (room1.markroom.equals("Yes")) {
            try {
                room1 = new Room1();
            } catch (IOException ex) {
                Logger.getLogger(people.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(people.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            room1.setVisible(true);
        }
    }//GEN-LAST:event_roomps1ActionPerformed

    private void roomps2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomps2ActionPerformed
        if (room2.markroom.equals("Yes")) {
            try {
                room2 = new Room2();
            } catch (IOException ex) {
                Logger.getLogger(people.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(people.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            room2.setVisible(true);
        }
    }//GEN-LAST:event_roomps2ActionPerformed

    private void roomps3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomps3ActionPerformed
        if (room3.markroom.equals("Yes")) {
            try {
                room3 = new Room3();
            } catch (IOException ex) {
                Logger.getLogger(people.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(people.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            room3.setVisible(true);
        }
    }//GEN-LAST:event_roomps3ActionPerformed

    private void roomps6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomps6ActionPerformed
        if (room6.markroom.equals("Yes")) {
            try {
                room6 = new Room6();
            } catch (IOException ex) {
                Logger.getLogger(people.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(people.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            room6.setVisible(true);
        }
    }//GEN-LAST:event_roomps6ActionPerformed

    private void roomps5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomps5ActionPerformed
        if (room5.markroom.equals("Yes")) {
            try {
                room5 = new Room5();
            } catch (IOException ex) {
                Logger.getLogger(people.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(people.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            room5.setVisible(true);
        }
    }//GEN-LAST:event_roomps5ActionPerformed

    private void roomps4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomps4ActionPerformed
        if (room4.markroom.equals("Yes")) {
            try {
                room4 = new Room4();
            } catch (IOException ex) {
                Logger.getLogger(people.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(people.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            room4.setVisible(true);
        }
    }//GEN-LAST:event_roomps4ActionPerformed

    private void roomalarm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomalarm1ActionPerformed
        try {
            room1.mp3.stop();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_roomalarm1ActionPerformed

    private void roomalarm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomalarm4ActionPerformed
        try {
            room4.mp3.stop();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_roomalarm4ActionPerformed

    private void roomalarm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomalarm5ActionPerformed

        try {
            room5.mp3.stop();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_roomalarm5ActionPerformed

    private void roomalarm6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomalarm6ActionPerformed
        try {
            room6.mp3.stop();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_roomalarm6ActionPerformed

    private void roomalarm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomalarm2ActionPerformed
        try {
            room2.mp3.stop();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_roomalarm2ActionPerformed

    private void roomalarm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomalarm3ActionPerformed

        try {
            room3.mp3.stop();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_roomalarm3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date1;
    public static javax.swing.JLabel fulltime1;
    public static javax.swing.JLabel fulltime2;
    public static javax.swing.JLabel fulltime3;
    public static javax.swing.JLabel fulltime4;
    public static javax.swing.JLabel fulltime5;
    public static javax.swing.JLabel fulltime6;
    public static javax.swing.JPanel fulltimepanel1;
    public static javax.swing.JPanel fulltimepanel2;
    public static javax.swing.JPanel fulltimepanel3;
    public static javax.swing.JPanel fulltimepanel4;
    public static javax.swing.JPanel fulltimepanel5;
    public static javax.swing.JPanel fulltimepanel6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JButton roomalarm1;
    private javax.swing.JButton roomalarm2;
    private javax.swing.JButton roomalarm3;
    private javax.swing.JButton roomalarm4;
    private javax.swing.JButton roomalarm5;
    private javax.swing.JButton roomalarm6;
    private javax.swing.JButton roomps1;
    private javax.swing.JButton roomps2;
    private javax.swing.JButton roomps3;
    private javax.swing.JButton roomps4;
    private javax.swing.JButton roomps5;
    private javax.swing.JButton roomps6;
    private javax.swing.JLabel serialid;
    // End of variables declaration//GEN-END:variables

}
